import uuid

from sqlalchemy import BigInteger, Boolean, Column, DateTime, ForeignKey, String, func
from sqlalchemy.dialects.mysql import CHAR as MySQLCHAR

from app.extensions import db


class Candidate(db.Model):
    __tablename__ = "candidates"

    id = Column(MySQLCHAR(32), primary_key=True, default=lambda: str(uuid.uuid4()).replace("-", ""))
    public_id = Column(String(36), unique=True, nullable=False, default=lambda: str(uuid.uuid4()))
    organization_id = Column(BigInteger, ForeignKey("organizations.id"), nullable=False, index=True)
    registration_number = Column(String(120), unique=True, nullable=True)
    full_name = Column(String(255), nullable=False)
    father_name = Column(String(255), nullable=True)
    mother_name = Column(String(255), nullable=True)
    gender = Column(String(50), nullable=True)
    date_of_birth = Column(DateTime, nullable=True)
    age = Column(String(20), nullable=True)
    aadhaar = Column(String(40), nullable=True)
    pan = Column(String(20), nullable=True)
    mobile = Column(String(20), nullable=True)
    alternative_mobile = Column(String(20), nullable=True)
    email = Column(String(255), nullable=True)
    category = Column(String(120), nullable=True)
    religion = Column(String(120), nullable=True)
    disability_status = Column(String(120), nullable=True)
    marital_status = Column(String(120), nullable=True)
    blood_group = Column(String(20), nullable=True)
    nationality = Column(String(120), nullable=True)
    current_address = Column(String(500), nullable=True)
    permanent_address = Column(String(500), nullable=True)
    village = Column(String(120), nullable=True)
    panchayat = Column(String(120), nullable=True)
    block = Column(String(120), nullable=True)
    district = Column(String(120), nullable=True)
    state = Column(String(120), nullable=True)
    pin = Column(String(20), nullable=True)
    latitude = Column(String(50), nullable=True)
    longitude = Column(String(50), nullable=True)
    qualification = Column(String(255), nullable=True)
    board = Column(String(255), nullable=True)
    passing_year = Column(String(20), nullable=True)
    percentage = Column(String(20), nullable=True)
    university = Column(String(255), nullable=True)
    training_center = Column(String(255), nullable=True)
    training_batch = Column(String(255), nullable=True)
    training_start_date = Column(DateTime, nullable=True)
    training_end_date = Column(DateTime, nullable=True)
    trainer = Column(String(255), nullable=True)
    sector = Column(String(255), nullable=True)
    trade = Column(String(255), nullable=True)
    nsqf_level = Column(String(50), nullable=True)
    course = Column(String(255), nullable=True)
    course_duration = Column(String(120), nullable=True)
    training_status = Column(String(80), nullable=False, default="training_started")
    bank_name = Column(String(255), nullable=True)
    account_number = Column(String(100), nullable=True)
    ifsc = Column(String(30), nullable=True)
    upi_id = Column(String(120), nullable=True)
    employer_name = Column(String(255), nullable=True)
    job_role = Column(String(255), nullable=True)
    salary = Column(String(40), nullable=True)
    joining_date = Column(DateTime, nullable=True)
    working_status = Column(String(80), nullable=True)
    location = Column(String(255), nullable=True)
    department = Column(String(255), nullable=True)
    manager = Column(String(255), nullable=True)
    hr_contact = Column(String(255), nullable=True)
    verification_status = Column(String(80), nullable=False, default="pending")
    exit_date = Column(DateTime, nullable=True)
    exit_reason = Column(String(255), nullable=True)
    batch_id = Column(MySQLCHAR(32), ForeignKey("batches.id"), nullable=True, index=True)
    scheme_id = Column(MySQLCHAR(32), ForeignKey("schemes.id"), nullable=True, index=True)
    offer_letter_url = Column(String(500), nullable=True)
    placement_proof_uploaded = Column(Boolean, nullable=False, default=False)
    password_hash = Column(String(255), nullable=True)
    account_status = Column(String(20), nullable=False, default="active")
    last_login_at = Column(DateTime, nullable=True)
    is_deleted = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)