import uuid

from sqlalchemy import BigInteger, Column, DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.mysql import CHAR as MySQLCHAR

from app.extensions import db


class Invoice(db.Model):
    """One billing record for one organization's subscription cycle.

    Nothing wrote to a billing table before this - Organization.payment_status
    was the only signal, set manually from the Subscription page. This table
    is the source of truth SRS FR-10 (Auto-Invoice Generation) and FR-09
    (Payment Gateway Integration) need: every invoice this organization has
    ever been issued, whether it was auto-generated by the billing cycle job
    or a manual adjustment, and how (if at all) it was paid.

    STATUSES:
      DRAFT     - generated but not yet sent/finalized (not used by the
                  auto-generation job below, but left available for manual
                  invoices created ad-hoc from the UI later).
      PENDING   - issued, awaiting payment.
      PAID      - payment confirmed (manually marked, or via gateway webhook
                  once app/services/payment_gateway.py is wired to a real key).
      OVERDUE   - past due_date and still unpaid. Set by the same job that
                  drives Organization.payment_status / auto-suspend.
      CANCELLED - voided, e.g. plan was changed before payment was collected.
    """

    __tablename__ = "invoices"

    STATUSES = ("DRAFT", "PENDING", "PAID", "OVERDUE", "CANCELLED")
    GATEWAYS = ("razorpay", "cashfree", "stripe", "manual")

    id = Column(MySQLCHAR(32), primary_key=True, default=lambda: str(uuid.uuid4()).replace("-", ""))
    invoice_number = Column(String(40), unique=True, nullable=False)  # e.g. INV-2026-000123, human-facing
    organization_id = Column(BigInteger, ForeignKey("organizations.id"), nullable=False, index=True)
    plan_id = Column(MySQLCHAR(32), ForeignKey("plans.id"), nullable=True, index=True)

    billing_cycle = Column(String(20), nullable=False, default="monthly")  # monthly | quarterly | yearly
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)

    amount = Column(Numeric(10, 2), nullable=False, default=0)
    # Set when this invoice is a prorated mid-cycle upgrade rather than a
    # normal full-period renewal - lets the UI/report show "prorated" instead
    # of implying the organization was charged full price twice.
    is_prorated = Column(Numeric(1), nullable=False, default=0)  # 0/1 flag, kept numeric like status ints elsewhere in this codebase
    proration_note = Column(String(255), nullable=True)  # e.g. "Upgraded Starter -> Professional, 14 days remaining"

    status = Column(String(20), nullable=False, default="PENDING")  # one of STATUSES

    payment_gateway = Column(String(20), nullable=True)  # one of GATEWAYS, null until paid
    gateway_reference = Column(String(255), nullable=True)  # gateway's transaction/payment id
    gateway_raw_response = Column(Text, nullable=True)  # last webhook/API payload, for support debugging

    due_date = Column(DateTime, nullable=False)
    issued_at = Column(DateTime, server_default=func.now(), nullable=False)
    paid_at = Column(DateTime, nullable=True)

    reminder_sent_at = Column(DateTime, nullable=True)  # last renewal-reminder email timestamp, avoids re-sending same day

    created_by = Column(MySQLCHAR(32), nullable=True)  # null when system-generated by the billing cycle job
    modified_by = Column(MySQLCHAR(32), nullable=True)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)