"""add organization_channel_settings table

Revision ID: 1b1e6302deba
Revises: fae1612fabb7
Create Date: 2026-09-18 10:27:33.034844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1e6302deba'
down_revision = 'fae1612fabb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_channel_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_api_key', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_api_key', sa.String(length=255), nullable=True),
    sa.Column('sms_sender_id', sa.String(length=50), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_channel_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_channel_settings_organization_id'), ['organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_channel_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_channel_settings_organization_id'))

    op.drop_table('organization_channel_settings')
    # ### end Alembic commands ###