"""add candidate_feedback table

Revision ID: 865e94383234
Revises: dd23651f58c8
Create Date: 2026-09-03 14:36:39.010761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '865e94383234'
down_revision = 'dd23651f58c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_feedback',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('candidate_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_feedback_candidate_id'), ['candidate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidate_feedback_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_permissions_created_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_permissions_modified_by'), type_='foreignkey')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_role_permissions_created_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_role_permissions_modified_by'), type_='foreignkey')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roles_modified_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_roles_created_by'), type_='foreignkey')

    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_upo_created_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_upo_modified_by'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission_overrides', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_upo_modified_by'), 'users', ['modified_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_upo_created_by'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_roles_created_by'), 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_roles_modified_by'), 'users', ['modified_by'], ['id'])

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_role_permissions_modified_by'), 'users', ['modified_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_role_permissions_created_by'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_permissions_modified_by'), 'users', ['modified_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_permissions_created_by'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('candidate_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_feedback_organization_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_feedback_candidate_id'))

    op.drop_table('candidate_feedback')
    # ### end Alembic commands ###
