"""fix organization_channel_settings modified_by column type

Revision ID: 8687e6b66f60
Revises: 1b1e6302deba
Create Date: 2026-09-18 10:45:27.493929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8687e6b66f60'
down_revision = '1b1e6302deba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_channel_settings', schema=None) as batch_op:
        batch_op.alter_column('modified_by',
               existing_type=mysql.BIGINT(),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('organization_channel_settings', schema=None) as batch_op:
        batch_op.alter_column('modified_by',
               existing_type=mysql.CHAR(length=32),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
